services:
    skeleton.module:
        class: 'Skeleton'
        factory: ['Module', 'getInstanceByName']
        arguments:
            - 'skeleton'

#    Installers
    install.tab:
        class: 'Invertus\Skeleton\Install\Tab'
        arguments:
            - '%module_settings%'

    installer:
        class: 'Invertus\Skeleton\Install\Installer'
        arguments:
            - '@skeleton.module'
            - '%module_settings%'

    uninstaller:
        class: 'Invertus\Skeleton\Install\Uninstaller'
        arguments:
            - '@skeleton.module'
            - '%module_settings%'